org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m

org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true

# TAMBAHKAN TOKEN RAHASIA DI SINI
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1Ijoic3VkYXJ0YWtpc3dhcmEiLCJhIjoiY21sMXI3NTU1MDl0bTNkc2QwaHAwZmRtcyJ9.I6uP_DuaPPNrie8jIeZjjQ
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
