package com.linkbit.billrt.model

import com.google.gson.annotations.SerializedName

data class PelangganDetail(
    val id_pelanggan: Int,
    val no_urut: Int,
    val nama_pelanggan: String,
    val alamat_pelanggan: String?,
    val telepon_pelanggan: String?,
    val email_pelanggan: String?,
    val wilayah: String?,
    val paket_internet: String?,
    val status_aktif: String,
    val pppoe_username: String?,
    val pppoe_password: String?,
    val pppoe_profile: String?,
    val pppoe_status: String,
    val static_ip: String?,
    val id_olt: Int,
    val pon_port: String?,
    val onu_index: String?,
    val onu_id: String?,
    val mac_address: String?,
    val signal_rx: String?,
    val signal_tx: String?,
    val odp_id: String?,
    val odp_port_id: String?,
    val tgl_daftar: String,
    val tgl_instalasi: String,
    val tgl_expired: String?,
    @SerializedName("tanggal_isolasi", alternate = ["tgl_isolasi", "tgl_jatuh_tempo", "jatuh_tempo"]) val tanggal_isolasi: String? = null,
    val last_paid: String?,
    val created_at: String,
    val latitude: Double,
    val longitude: Double,
    val foto_lokasi: String?,
    val teknisi: String?,
    val notes: String?
)
