package com.linkbit.billrt.model

import com.google.gson.annotations.SerializedName

data class TimelineResponse(
    @SerializedName("status")
    val status: Boolean,
    @SerializedName("tahun")
    val tahun: Int? = null,
    @SerializedName("profil")
    val profil: Profil?,
    @SerializedName("data")
    val data: List<HistoryTagihan>?
)

data class Profil(
    @SerializedName("id_pelanggan")
    val idPelanggan: Int,
    @SerializedName("nama_pelanggan")
    val namaPelanggan: String,
    @SerializedName("wilayah")
    val wilayah: String? = null,
    @SerializedName("installation_date")
    val installationDate: String? = null
)

data class HistoryTagihan(
    @SerializedName("id_tagihan", alternate = ["no_invoice"]) val idTagihan: Any? = null,
    @SerializedName("id_pelanggan") val idPelanggan: Any? = null,
    @SerializedName("bulan_tagihan") val bulanTagihan: Any? = null,
    @SerializedName("tahun_tagihan") val tahunTagihan: Any? = null,
    @SerializedName("jumlah_tagihan", alternate = ["jumlah"]) val jumlahTagihan: Any? = null,
    @SerializedName("tanggal_isolasi", alternate = ["tgl_isolasi", "tanggal_isolasi_raw", "tgl_jatuh_tempo", "jatuh_tempo"]) val tglJatuhTempo: String? = null,
    @SerializedName("status_tagihan", alternate = ["status"]) val statusTagihan: Any? = null,
    @SerializedName("catatan_tagout") val catatanTagout: String? = null,
    @SerializedName("deskripsi") val deskripsi: String? = null,
    @SerializedName("auto_generated") val autoGenerated: String? = null,
    @SerializedName("generated_by") val generatedBy: String? = null,
    @SerializedName("created_at") val createdAt: String? = null,
    @SerializedName("updated_at") val updatedAt: String? = null,
    @SerializedName("tanggal_bayar", alternate = ["tanggal", "tanggal_raw"]) val tanggalBayar: String? = null,
    @SerializedName("metode_bayar", alternate = ["metode"]) val metodeBayar: Any? = null,
    @SerializedName("id_user_pencatat") val idUserPencatat: Any? = null,
    @SerializedName("nama_pencatat", alternate = ["pencatat"]) val namaPencatat: String? = null, 
    @SerializedName("harga_paket") val hargaPaket: Double? = null,
    @SerializedName("nama_paket") val namaPaket: String? = null,
    @SerializedName("nama_pelanggan") val namaPelanggan: String? = null,
    @SerializedName("installation_date") val installationDate: String? = null,
    @SerializedName("nama_wilayah") val namaWilayah: String? = null,
    @SerializedName("bulan_nama") val bulanNama: String? = null,
    @SerializedName("status_text") val statusText: String? = null
) {
    fun getJumlahDouble(): Double {
        return when (jumlahTagihan) {
            is Number -> jumlahTagihan.toDouble()
            is String -> jumlahTagihan.toDoubleOrNull() ?: 0.0
            else -> 0.0
        }
    }

    fun isLunas(): Boolean {
        val st = statusTagihan?.toString()?.lowercase()?.trim() ?: ""
        val txt = statusText?.lowercase()?.trim() ?: ""
        return st == "1" || st == "lunas" || st == "true" || txt == "lunas" || txt.contains("lunas")
    }

    fun isTagout(): Boolean {
        val st = statusTagihan?.toString()?.lowercase()?.trim() ?: ""
        val txt = statusText?.lowercase()?.trim() ?: ""
        return st == "2" || st == "tagout" || txt.contains("tagout")
    }
}

data class TimelineItem(
    @SerializedName("title")
    val title: String,
    @SerializedName("subtitle")
    val subtitle: String,
    @SerializedName("date_display")
    val dateDisplay: String,
    @SerializedName("status_text")
    val statusText: String,
    @SerializedName("dot_color")
    val dotColor: String,
    @SerializedName("description")
    val description: String,
    @SerializedName("has_invoice")
    val hasInvoice: Boolean,
    @SerializedName("id_tagihan")
    val idTagihan: String?,
    @SerializedName("admin_pencatat")
    val adminPencatat: String? 
)
