package com.linkbit.billrt.model

import com.google.gson.annotations.SerializedName

data class TimelineResponse(
    @SerializedName("status")
    val status: Boolean,
    @SerializedName("tahun")
    val tahun: Int? = null,
    @SerializedName("profil")
    val profil: Profil?,
    @SerializedName("data")
    val data: List<HistoryTagihan>?
)

data class Profil(
    @SerializedName("id_pelanggan")
    val idPelanggan: Int,
    @SerializedName("nama_pelanggan")
    val namaPelanggan: String,
    @SerializedName("wilayah")
    val wilayah: String? = null,
    @SerializedName("installation_date")
    val installationDate: String? = null
)

data class HistoryTagihan(
    @SerializedName("id_tagihan") val idTagihan: Any,
    @SerializedName("id_pelanggan") val idPelanggan: Int,
    @SerializedName("bulan_tagihan") val bulanTagihan: Int,
    @SerializedName("tahun_tagihan") val tahunTagihan: Int,
    @SerializedName("jumlah_tagihan") val jumlahTagihan: Double,
    @SerializedName("tgl_jatuh_tempo") val tglJatuhTempo: String? = null,
    @SerializedName("status_tagihan") val statusTagihan: Int,
    @SerializedName("catatan_tagout") val catatanTagout: String? = null,
    @SerializedName("deskripsi") val deskripsi: String? = null,
    @SerializedName("auto_generated") val autoGenerated: String? = null,
    @SerializedName("generated_by") val generatedBy: String? = null,
    @SerializedName("created_at") val createdAt: String? = null,
    @SerializedName("updated_at") val updatedAt: String? = null,
    @SerializedName("tanggal_bayar") val tanggalBayar: String? = null,
    @SerializedName("metode_bayar") val metodeBayar: Any? = null,
    @SerializedName("id_user_pencatat") val idUserPencatat: Int? = null,
    @SerializedName("nama_pencatat") val namaPencatat: String? = null, 
    @SerializedName("harga_paket") val hargaPaket: Double? = null,
    @SerializedName("nama_paket") val namaPaket: String? = null,
    @SerializedName("nama_pelanggan") val namaPelanggan: String? = null,
    @SerializedName("installation_date") val installationDate: String? = null,
    @SerializedName("nama_wilayah") val namaWilayah: String? = null,
    @SerializedName("bulan_nama") val bulanNama: String? = null,
    @SerializedName("status_text") val statusText: String? = null
)

data class TimelineItem(
    @SerializedName("title")
    val title: String,
    @SerializedName("subtitle")
    val subtitle: String,
    @SerializedName("date_display")
    val dateDisplay: String,
    @SerializedName("status_text")
    val statusText: String,
    @SerializedName("dot_color")
    val dotColor: String,
    @SerializedName("description")
    val description: String,
    @SerializedName("has_invoice")
    val hasInvoice: Boolean,
    @SerializedName("id_tagihan")
    val idTagihan: String?,
    @SerializedName("admin_pencatat")
    val adminPencatat: String? 
)
